### ISSUE TITLE
Add recommended way to upgrade Docker container

### ISSUE THREAD

**Issue by kingo55** [amancevice/caravel#3]
Awesome container... Might be helpful to new Docker users (myself included), to provide some instructions on upgrading the Docker container:

As far as I know, upgrading should be just:
1. Stop existing container: `docker stop caravel`
2. Remove existing container: `docker rm caravel`
3. Pull new container from repo: `docker pull amacevice/caravel`
4. Run new container linking it up to the existing Docker storage on the host used for the previous container (as per instructions on front page)
5. Execute Caravel upgrade function in the container: `caravel db upgrade`

Is this correct?

**Comment by amancevice** [comment]
Yeah, that all looks correct  to me. Good suggestion.

**Comment by amancevice** [comment]
Added a bit to the README
