### ISSUE TITLE
Use sqlite configuration with error "unable to open database file"

### ISSUE THREAD

**Issue by licq** [amancevice/caravel#9]
When I use the sqlite configuration as described in the documentation:

docker run --detach --name caravel \
    --env SECRET_KEY="mySUPERsecretKEY" \
    --env SQLALCHEMY_DATABASE_URI="sqlite:////home/caravel/caravel.db" \
    --publish 8088:8088 \
    --volume ~/caravel/caravel.db:/home/caravel/caravel.db \
    amancevice/caravel

the container exits and docker logs shows the error:

2016-05-30 12:42:15,123:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (sqlite3.OperationalError) unable to open database file

I think the cause is the permission of the folder /home/caravel/caravel.db , because its owner is root and the runner is caravel.

**Comment by amancevice** [comment]
I'll take a look at this. For now you can get around this by mounting `~/caravel:/home/caravel` instead of mounting the `.db` file directly.

**Comment by amancevice** [comment]
Okay, I think i fixed the issue in the latest commit. I updated the README as well.

**Comment by jackpgao** [comment]
Same problem  with amancevice/superset:0.22.1

**Comment by amancevice** [comment]
Can you show me the command you're using to bring up the container, @jackpgao ?

**Comment by jackpgao** [comment]
```
docker run -it --rm --name superset \
               --env SECRET_KEY="mySUPERsecretKEY" \
               --env SQLALCHEMY_DATABASE_URI="mysql://user:pass@mxq@host:port/db" \
               --publish 8089:8088 \
               amancevice/superset:0.22.1

```

**Comment by amancevice** [comment]
Using ENV variables is no longer supported as of the [0.15.0 release](https://github.com/amancevice/superset/releases/tag/0.15.0). You need to configure these values by mounting in your own `superset_config.py`.

FYI, This repo is dead as the app is no longer called caravel and you should go to https://github.com/amancevice/superset for instructions on using the new code.

**Comment by jackpgao** [comment]
@amancevice  Thanks~ I got it. It's really a good project.
